name: Build and Package PyQt6 app

on:
  push:
    branches: [ main ]
    
jobs:
  build_and_package_windows:
    name: build for windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build PyQt6 app
        run: |
          pyinstaller -n "GPTChatClient" --windowed --icon="icon.ico" QT_Client_Chat.py
      
      - name: Upload Windows package to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: GPTChatClient_windows
          path: dist\GPTChatClient
          
          
  build_and_package_mac:
    name: build for mac
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          brew install create-dmg
      
      - name: Build PyQt6 app
        run: |
          pyinstaller -n "GPTChatClient" --windowed --icon="icon.icns" QT_Client_Chat.py
      
      - name: Run script to create dmg
        run: |
          bash create_dmg.sh
      
      - name: Upload Mac package to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: GPTChatClient_mac
          path: dist/GPTChatClient.dmg
    
    
    
